#!/bin/bash

# Windows Subsystem Launch (it's a terrible portmanteau, I know)

source "$wslfiles/paths.sh"

# if cmdrc elevated; then
#   UACe=true
# else
#   UACe=false
# fi
# export UACe

if $interactive; then
  source "$wslfiles/aliases.sh"
fi
